// ============================================
// AURA - Summary Page
// ============================================

import React, { useEffect, useState } from 'react';
import { SummaryCard } from '../components/summary/SummaryCard';
import { FindingsTable } from '../components/summary/FindingsTable';
import { RedFlagAlert } from '../components/summary/RedFlagAlert';
import { TranscriptView } from '../components/summary/TranscriptView';
import { getConsultationDetails } from '../services/api';
import { ConsultationSummary } from '../types';

interface SummaryPageProps {
  consultationId: string;
  onBack: () => void;
}

export function SummaryPage({ consultationId, onBack }: SummaryPageProps) {
  const [data, setData] = useState<ConsultationSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadSummary() {
      try {
        const result = await getConsultationDetails(consultationId);
        setData(result);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    loadSummary();
  }, [consultationId]);

  const handleExportReport = () => {
    if (!data) return;

    const report = `
================================================================================
                    VIRTUAL SCRIBE ASSISTANT - CLINICAL CONSULTATION REPORT
================================================================================
Report Date: ${new Date(data.consultation.started_at).toLocaleDateString()}
Consultation Time: ${new Date(data.consultation.started_at).toLocaleTimeString()}
Status: ${data.consultation.status.toUpperCase()}
Triage Risk Assessment: ${data.summary ? data.summary.recommended_triage_level.toUpperCase() : 'ROUTINE'}
================================================================================

1. ADVANCED CLINICAL EVALUATION & ACTION PLAN
--------------------------------------------------------------------------------
${data.summary?.summary_text || 'No clinical evaluation available.'}

2. SPECIALIST REFERRAL, DIAGNOSTICS & SAFETY GUIDANCE
--------------------------------------------------------------------------------
${data.summary?.clinical_impression || 'No specialist guidance available.'}

3. EXTRACTED CLINICAL DATA SUMMARY
--------------------------------------------------------------------------------
• Primary Complaint: ${data.findings.chiefComplaint || 'Not reported'}
• Presenting Symptoms: ${data.findings.symptoms.join(', ') || 'None reported'}
• Onset & Progression: ${data.findings.onset || 'Not reported'}
• Symptom Duration: ${data.findings.duration || 'Not reported'}
• Severity Scale: ${data.findings.severity || 'Not reported'}
• Associated Symptoms: ${data.findings.associatedSymptoms.join(', ') || 'None reported'}
• Detected Red Flags: ${data.findings.redFlags.join(', ') || 'None detected'}
• Medical History: ${data.findings.medicalHistory || 'Not reported'}
• Current Medications: ${data.findings.medications.join(', ') || 'None reported'}
• Known Allergies: ${data.findings.allergies.join(', ') || 'None reported'}

4. FULL CONSULTATION TRANSCRIPT
--------------------------------------------------------------------------------
${data.messages
  .map(
    (m) =>
      `[${new Date(m.createdAt).toLocaleTimeString()}] ${
        m.role === 'assistant' ? 'Virtual Scribe Assistant' : 'PATIENT'
      }:\n${m.content}`
  )
  .join('\n\n')}

================================================================================
MEDICAL DISCLAIMER:
This document is generated by Virtual Scribe Assistant for informative, 
triage, and clinical documentation support. It does not constitute a formal 
medical prescription. Always consult a qualified physician for clinical care.
================================================================================
`.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `virtual-scribe-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="summary-page">
        <div className="loading-state">
          <div className="spinner large"></div>
          <p>Loading consultation summary...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="summary-page">
        <div className="error-state">
          <h3>Error Loading Summary</h3>
          <p>{error || 'Consultation not found.'}</p>
          <button onClick={onBack} className="btn btn-primary">
            Go Back
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="summary-page">
      <header className="summary-header">
        <button onClick={onBack} className="btn btn-ghost btn-sm back-btn">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <line x1="19" y1="12" x2="5" y2="12" />
            <polyline points="12 19 5 12 12 5" />
          </svg>
          Back
        </button>
        <h2>Consultation Summary</h2>
        <button
          onClick={handleExportReport}
          className="btn btn-primary btn-sm"
          id="export-report-btn"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Export Report
        </button>
      </header>

      <div className="summary-content">
        {/* Red Flag Alert */}
        <RedFlagAlert
          redFlags={data.findings.redFlags}
          triageLevel={data.summary?.recommended_triage_level || 'routine'}
        />

        {/* Summary Card */}
        {data.summary && (
          <SummaryCard
            summaryText={data.summary.summary_text}
            clinicalImpression={data.summary.clinical_impression}
            triageLevel={data.summary.recommended_triage_level}
            startedAt={data.consultation.started_at}
            completedAt={data.consultation.completed_at}
          />
        )}

        {/* Findings Table */}
        <FindingsTable findings={data.findings} />

        {/* Transcript */}
        <TranscriptView messages={data.messages} />
      </div>
    </div>
  );
}
